# Generated by Django 4.2.1 on 2023-06-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('hot', 'hot'), ('best', 'best'), ('new', 'new')], default='new', on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
