# Generated by Django 4.2.1 on 2023-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('hot', 'hot'), ('best', 'best'), ('new', 'new')], default='new', on_delete=django.db.models.deletion.PROTECT, to='blog.category', to_field='name'),
        ),
    ]
