# Generated by Django 4.2.1 on 2023-06-22 07:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
