# Generated by Django 4.2.1 on 2023-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('hot', 'hot'), ('best', 'best'), ('new', 'new')], max_length=100, unique=True),
        ),
    ]
