# Generated by Django 4.2.1 on 2023-06-22 11:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='posts/default.jpg', null=True, upload_to=blog.models.user_directory_path, verbose_name='Image'),
        ),
    ]
