# Generated by Django 4.2.1 on 2023-06-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
